from __future__ import annotations

CUSTOM_NODE_RUNTIME_DEPS: dict[str, list[str]] = {
    "ComfyUI-Prompt-Combinator": [],
    "ComfyUI-qwenmultiangle": ["transformers", "accelerate"],
    "ComfyUI-SCAIL-Pose": [],
    "ComfyUI-SeedVR2_VideoUpscaler": [],
    "audio-separation-nodes-comfyui": ["demucs", "openunmix"],
    "ComfyUI-Inspire-Pack": [],
    "ComfyUI-Impact-Subpack": ["ultralytics"],
    "ComfyUI_IPAdapter_plus": [],
    "ComfyUI-Impact-Pack": ["onnxruntime", "ultralytics", "segment-anything"],
    "ComfyUI_LayerStyle": ["iopaint", "color-matcher", "blend-modes", "pymatting"],
    "ComfyUI-Advanced-ControlNet": [],
    "ComfyUI_AudioTools": ["librosa", "soundfile", "pydub"],
    "ComfyUI-segment-anything-2": [],
    "ComfyMath": [],
    "ComfyUI_essentials": [],
    "ComfyUI-Florence2": ["transformers", "timm"],
    "rgthree-comfy": [],
    "ComfyUI-Flux-Continuum": [],
    "ComfyUI-WanVideoWrapper": ["mediapipe<=0.10.21", "onnx", "onnxruntime"],
    "ComfyUI-Frame-Interpolation": [],
    "RES4LYF": [],
    "Comfyui-Resolution-Master": [],
    "ComfyUI-WanAnimatePreprocess": [],
    "ComfyUI-Crystools": [],
    "ComfyUI-Detail-Daemon": [],
    "ComfyUI-GGUF": ["gguf"],
    "ComfyUI_UltimateSDUpscale": [],
    "ComfyUI_Fill-Nodes": ["anthropic", "openai", "google-generativeai"],
    "ComfyUI_Fill-ChatterBox": [],
    "ComfyUI-KJNodes": [],
    "ComfyUI-NormalCrafterWrapper": [],
    "ComfyUI-FlashVSR_Ultra_Fast": [],
    "ComfyUI-Lotus": [],
    "Bjornulf_custom_nodes": ["TTS", "edge-tts", "piper-tts"],
    "comfyui_controlnet_aux": ["scikit-learn", "mediapipe<=0.10.21", "protobuf>=4.25.3,<5", "trimesh[easy]", "onnx", "onnxruntime"],
    "ControlAltAI-Nodes": ["scikit-learn", "mediapipe<=0.10.21", "protobuf>=4.25.3,<5", "trimesh[easy]"],
    "ComfyUI-DepthAnythingV2": [],
    "ComfyUI-VideoHelperSuite": [],
    "ComfyUI-Manager": [],
    "comfyui-easy-use": ["cpm_kernels"],
    "ComfyUI_Custom_Nodes_AlekPet": [],
    "comfyui_layerstyle": ["iopaint"],
}
